# Generated by Django 4.1.4 on 2023-01-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk', '-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk', '-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk', '-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectzones', to='base.project')),
            ],
            options={
                'ordering': ['pk', '-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TargetFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_floor_cycle', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.floor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetfloors', to='base.project')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.zone')),
            ],
            options={
                'ordering': ['floor__pk', '-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectfloors', to='base.project'),
        ),
        migrations.AddField(
            model_name='block',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectblocks', to='base.project'),
        ),
        migrations.CreateModel(
            name='ActualFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_floor_cycle', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.floor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualfloors', to='base.project')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.zone')),
            ],
            options={
                'ordering': ['floor__pk', '-updated', '-created'],
            },
        ),
    ]
