# Generated by Django 4.1.6 on 2023-02-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='collected',
            new_name='date_collected',
        ),
    ]
